complexity:

  LongParameterList:
    ignoreAnnotated:
      - 'androidx.compose.runtime.Composable'

  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - 'androidx.compose.ui.tooling.preview.Preview'


naming:

# Not mergeable, defined in main config.
#  FunctionMaxLength:
#    ignoreAnnotated:
#      - 'androidx.compose.ui.tooling.preview.Preview*'
#      - 'net.twisterrob.astro.compose.preview.Preview*'

  FunctionNaming:
    ignoreAnnotated:
      - 'androidx.compose.runtime.Composable'

  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'


style:

  UnusedPrivateMember:
    ignoreAnnotated:
      - 'androidx.compose.ui.tooling.preview.Preview*'
      - 'net.twisterrob.astro.compose.preview.Preview*'


compose: # Kode (ru.kode:detekt-rules-compose)
  ComposableEventParameterNaming:
    # Enable default-disabled rule.
    active: true
  TopLevelComposableFunctions:
    # Enable default-disabled rule.
    active: true
  ConditionCouldBeLifted:
    # Enable default-disabled rule.
    active: true


Compose: # Twitter/nlopez (io.nlopez.compose.rules:detekt)
  Material2:
    # Enable default-disabled rule.
    active: true
  PreviewNaming:
    # Enable default-disabled rule.
    active: true
  UnstableCollections:
    # Enable default-disabled rule.
    active: true
